"""empty message

Revision ID: 5ed28fd0646b
Revises: 7a0d310f2904
Create Date: 2023-07-13 14:17:55.170459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed28fd0646b'
down_revision = '7a0d310f2904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textfields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('textfields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_textfields_name'), ['name'], unique=False)

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_index('ix_about_name')

    op.drop_table('about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.create_index('ix_about_name', ['name'], unique=False)

    with op.batch_alter_table('textfields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_textfields_name'))

    op.drop_table('textfields')
    # ### end Alembic commands ###
