"""empty message

Revision ID: 7a0d310f2904
Revises: e0b2417fe509
Create Date: 2023-07-13 14:16:50.104889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0d310f2904'
down_revision = 'e0b2417fe509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_about_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_about_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
