"""empty message

Revision ID: 7ae1feb38dd7
Revises: 6f2448f08a25
Create Date: 2025-03-25 15:56:44.647194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae1feb38dd7'
down_revision = '6f2448f08a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_name_min', sa.String(length=128), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_name_min', sa.String(length=128), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_name_min', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('thumb_name_min')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('thumb_name_min')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('thumb_name_min')

    # ### end Alembic commands ###
